name: Archive NVIDIA Blogs

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday
  workflow_dispatch:       # Manual trigger

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add posts/
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Archive update: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            git push
          fi
